### ISSUE TITLE
Release 0.2 crashing at the end of the ConditionVariable.cpp example

### ISSUE THREAD

**Issue by solanik** [samanbarghi/uThreads#29]
I'm trying to test this on latest release, I've run ConditionVariable example, but I've got crash on kThread destructor. Here's the backtrace:
#0  0x00007ffff728f418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff729101a in __GI_abort () at abort.c:89
#2  0x00007ffff78cb5cd in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff78c9376 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff78c93c1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7bcd03d in std::thread::~thread (this=0x7fffffff4108,  __in_chrg=<optimized out>) at /usr/include/c++/6/thread:145
#6  kThread::~kThread (this=0x7fffffff40f0, __in_chrg=<optimized out>) at src/runtime/kThread.cpp:56
#7  0x00000000004020ea in main ()

**Comment by samanbarghi** [comment]
@solanik can you please use the dev branch and run the same test to see if it still happens? a lot of bugs have been fixed in dev branch, and I think this was one of them.

**Comment by solanik** [comment]
I've tried it on dev branch and it's ok there. When do you plan to merge this dev branch to master?

**Comment by samanbarghi** [comment]
@solanik Great! It is almost ready to be merged to master, for a proper release I need to update the documentation and provide a proper changelog and test the dev branch to make sure no such bugs slip into the released version. But I say in a week or two.

**Comment by samanbarghi** [comment]
@solanik I finally found some time to merge commits and update the documentation and issue a new release. You can find it in the master branch, or here https://github.com/samanbarghi/uThreads/tree/v0.3.0
