### ISSUE TITLE
Instructions for reproducing benchmarks in README?

### ISSUE THREAD

**Issue by hq6** [samanbarghi/uThreads#32]
You show some very nice throughput numbers on the README for the webserver, but I cannot directly compare your library to others on my system since it is not the same hardware.

Can you please provide instructions for reproducing the experiments, including the version of the client you used, how you configured it, and what kind of network you were running over?

**Comment by samanbarghi** [comment]
Hi @hq6, I will make a post about it soon in the wiki or on my blog, and put the link here so you can run on your machine and compare the results.

**Comment by hq6** [comment]
Hi @samanbarghi, when you write that post, can you also mention how `node.js` is configured in this experiment? In particular, I'm curious about whether node is serving from disk (ie filesystem cache) or memory directly.

**Comment by samanbarghi** [comment]
@hq6 these are the steps I took for the benchmark. You can find the files I used as well: https://github.com/samanbarghi/httpbenchmarks

For nodejs and fasthttp responses are being served from the memory. For cppsp I might need to change my approach. As I said in the performance comparisons, I did not optimise any of these frameworks, and there might be space to improve the server code. Let me know if you did any optimisations and got different results and I update the code accordingly.
